// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPSJ3bRGZ6xJtiiFaD9mxCa1_FXbT77Pg',
    appId: '1:313284362971:web:075546f37c3e4dd7b082fe',
    messagingSenderId: '313284362971',
    projectId: 'authentication-8e330',
    authDomain: 'authentication-8e330.firebaseapp.com',
    storageBucket: 'authentication-8e330.firebasestorage.app',
    measurementId: 'G-WHV07DL5BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKvTVZeejc7xxXrxne11JkKR2D98fljYU',
    appId: '1:313284362971:android:619d7538119a1624b082fe',
    messagingSenderId: '313284362971',
    projectId: 'authentication-8e330',
    storageBucket: 'authentication-8e330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXaFjE3id8_4b_tO2B575P-HsxshwNUs',
    appId: '1:313284362971:ios:c567edd12c603f5ab082fe',
    messagingSenderId: '313284362971',
    projectId: 'authentication-8e330',
    storageBucket: 'authentication-8e330.firebasestorage.app',
    androidClientId: '313284362971-6v5qienqo1u9hrnbqoi715eppj1c1h52.apps.googleusercontent.com',
    iosClientId: '313284362971-vgg6q5p577f72ocrjrha3rd4tgo7tuck.apps.googleusercontent.com',
    iosBundleId: 'com.example.nikeEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXaFjE3id8_4b_tO2B575P-HsxshwNUs',
    appId: '1:313284362971:ios:c567edd12c603f5ab082fe',
    messagingSenderId: '313284362971',
    projectId: 'authentication-8e330',
    storageBucket: 'authentication-8e330.firebasestorage.app',
    androidClientId: '313284362971-6v5qienqo1u9hrnbqoi715eppj1c1h52.apps.googleusercontent.com',
    iosClientId: '313284362971-vgg6q5p577f72ocrjrha3rd4tgo7tuck.apps.googleusercontent.com',
    iosBundleId: 'com.example.nikeEcom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPSJ3bRGZ6xJtiiFaD9mxCa1_FXbT77Pg',
    appId: '1:313284362971:web:2776b2eed91b71eab082fe',
    messagingSenderId: '313284362971',
    projectId: 'authentication-8e330',
    authDomain: 'authentication-8e330.firebaseapp.com',
    storageBucket: 'authentication-8e330.firebasestorage.app',
    measurementId: 'G-SNJ9P8CVZ4',
  );
}
